### PR TITLE
Ms project1 branch

### PR DESCRIPTION
**Pull request by GittBUB**
This merge will add functioning map to the listofspace.html

### CODE REVIEW

**Comment by GittBUB** [comment]
Added additional documentation to listofspace.html and increased initial view of map to cover all of NYC. Map zoom is minimized when zip code is entered.

**Comment by GittBUB** [comment]
Adding firebase code for map.

**Comment by GittBUB** [comment]
Firebase code added to map script.

**Comment by zednon** [comment]
Great work you do a really amazing job.

**Review by zednon — APPROVED** [review]

**Pull request merged**
